/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClueMakerRouteImport } from './routes/clueMaker'
import { Route as ClueGuesserRouteImport } from './routes/clueGuesser'
import { Route as IndexRouteImport } from './routes/index'

const ClueMakerRoute = ClueMakerRouteImport.update({
  id: '/clueMaker',
  path: '/clueMaker',
  getParentRoute: () => rootRouteImport,
} as any)
const ClueGuesserRoute = ClueGuesserRouteImport.update({
  id: '/clueGuesser',
  path: '/clueGuesser',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clueGuesser': typeof ClueGuesserRoute
  '/clueMaker': typeof ClueMakerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clueGuesser': typeof ClueGuesserRoute
  '/clueMaker': typeof ClueMakerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clueGuesser': typeof ClueGuesserRoute
  '/clueMaker': typeof ClueMakerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clueGuesser' | '/clueMaker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clueGuesser' | '/clueMaker'
  id: '__root__' | '/' | '/clueGuesser' | '/clueMaker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClueGuesserRoute: typeof ClueGuesserRoute
  ClueMakerRoute: typeof ClueMakerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clueMaker': {
      id: '/clueMaker'
      path: '/clueMaker'
      fullPath: '/clueMaker'
      preLoaderRoute: typeof ClueMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clueGuesser': {
      id: '/clueGuesser'
      path: '/clueGuesser'
      fullPath: '/clueGuesser'
      preLoaderRoute: typeof ClueGuesserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClueGuesserRoute: ClueGuesserRoute,
  ClueMakerRoute: ClueMakerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
