/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteImport } from './routes/_game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameClueMakerRouteImport } from './routes/_game/clueMaker'
import { Route as GameClueGuesserRouteImport } from './routes/_game/clueGuesser'

const GameRoute = GameRouteImport.update({
  id: '/_game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameClueMakerRoute = GameClueMakerRouteImport.update({
  id: '/clueMaker',
  path: '/clueMaker',
  getParentRoute: () => GameRoute,
} as any)
const GameClueGuesserRoute = GameClueGuesserRouteImport.update({
  id: '/clueGuesser',
  path: '/clueGuesser',
  getParentRoute: () => GameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clueGuesser': typeof GameClueGuesserRoute
  '/clueMaker': typeof GameClueMakerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clueGuesser': typeof GameClueGuesserRoute
  '/clueMaker': typeof GameClueMakerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_game': typeof GameRouteWithChildren
  '/_game/clueGuesser': typeof GameClueGuesserRoute
  '/_game/clueMaker': typeof GameClueMakerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clueGuesser' | '/clueMaker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clueGuesser' | '/clueMaker'
  id: '__root__' | '/' | '/_game' | '/_game/clueGuesser' | '/_game/clueMaker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_game': {
      id: '/_game'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game/clueMaker': {
      id: '/_game/clueMaker'
      path: '/clueMaker'
      fullPath: '/clueMaker'
      preLoaderRoute: typeof GameClueMakerRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/clueGuesser': {
      id: '/_game/clueGuesser'
      path: '/clueGuesser'
      fullPath: '/clueGuesser'
      preLoaderRoute: typeof GameClueGuesserRouteImport
      parentRoute: typeof GameRoute
    }
  }
}

interface GameRouteChildren {
  GameClueGuesserRoute: typeof GameClueGuesserRoute
  GameClueMakerRoute: typeof GameClueMakerRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameClueGuesserRoute: GameClueGuesserRoute,
  GameClueMakerRoute: GameClueMakerRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
